local inspect_main = inspectWeapon_main

local ammo_check_chance_track_handlers

local function ammo_check_chance_track_ui_hook(anchor, handlers, attributes, flags)
	if handlers == nil then
		return
	end

	ammo_check_chance_track_handlers = handlers
	local value = ui_mcm.get("inspectWeapon/ammoCheckChance")
	ammo_check_chance_track_handlers.txt:SetText(value .. "%")
end

local function ammo_check_chance_track_on_selection(path, option, value, attributes)
	if ammo_check_chance_track_handlers.txt == nil then
		return
	end

	ammo_check_chance_track_handlers.txt:SetText(value .. "%")
end

local function on_key_press(key)
	if key ~= inspect_main.inspect_options.keybind then 
		return 
	end

	if inspect_main.inspect_options.key_input_mode == 0 then
		ui_mcm.simple_press("inspectWeapon", key, inspect_main.inspect_weapon)
		return
	end

	if inspect_main.inspect_options.key_input_mode == 1 and ui_mcm.double_tap("inspectWeapon", key) then
		inspect_main.inspect_weapon()
	end
end

local function on_key_hold(key)
	if key ~= inspect_main.inspect_options.keybind then 
		return 
	end

	if inspect_main.inspect_options.key_input_mode == 2 and ui_mcm.key_hold("inspectWeapon", key) then
		inspect_main.inspect_weapon()
	end
end

local function on_option_change(mcm)
	if mcm then
		inspect_main.inspect_options.keybind = ui_mcm.get("inspectWeapon/keybind")
		inspect_main.inspect_options.key_input_mode = ui_mcm.get("inspectWeapon/keyInputMode")
		inspect_main.inspect_options.enable_dof = ui_mcm.get("inspectWeapon/inspectDoF")
		inspect_main.inspect_options.remove_ui = ui_mcm.get("inspectWeapon/inspectRemoveUI")
		inspect_main.inspect_options.disable_idle_animation = ui_mcm.get("inspectWeapon/disableIdleAnimation")
		inspect_main.inspect_options.use_ammo_check_animation = ui_mcm.get("inspectWeapon/useAmmoCheckAnimation")

		if inspect_main.inspect_options.use_ammo_check_animation then
			inspect_main.inspect_options.ammo_check_chance = ui_mcm.get("inspectWeapon/ammoCheckChance")
		else
			inspect_main.inspect_options.ammo_check_chance = 0
		end
    end
end

function on_mcm_load()
	local options = 
	{
		id = "inspectWeapon", sh = true,
		gr = 
		{
			{ id = "inspectWeapon", type = "slide", link = "ui_options_slider_disguise", text = "ui_mcm_menu_inspectWeapon", size = { 512,50 }, spacing = 20 },
			{ id = "keybind", type = "key_bind", val = 2, def = DIK_keys.DIK_R },
			{ id = "keyInputMode", type = ui_mcm.kb_mod_radio, val = 2, def = 2, text = "ui_mcm_inspectWeapon_keyInputMode", 
				content = { { 0, "mcm_kb_mode_press" }, { 1, "mcm_kb_mode_dtap" }, { 2, "mcm_kb_mode_hold" } }
			},
			{ id = "divider1", type= "line" },
			{ id = "inspectDoF", type = "check", val = 1, def = true, text = "ui_mcm_inspectWeapon_inspectDoF" },
			{ id = "inspectRemoveUI", type = "check", val = 1, def = true, text = "ui_mcm_inspectWeapon_inspectRemoveUI" },
			{ id = "divider2", type= "line" },
			{ id = "disableIdleAnimation", type = "check", val = 1, def = true, text = "ui_mcm_inspectWeapon_disableIdleAnimation" },
			{ id = "divider3", type= "line" },
			{ id = "useAmmoCheckAnimation", type = "check", val = 1, def = true, text = "ui_mcm_inspectWeapon_useAmmoCheckAnimation" },
			{ id = "ammoCheckChance", type = "track", val = 2, def = 33, min = 0, max = 100, step = 1, text = "ui_mcm_inspectWeapon_ammoCheckChance",
				on_selection_functor = { ammo_check_chance_track_on_selection },
				ui_hook_functor = { ammo_check_chance_track_ui_hook }
			}
		}
	}
	return options
end

function on_game_start()
	RegisterScriptCallback("on_key_press", on_key_press)
	RegisterScriptCallback("on_key_hold", on_key_hold)
	RegisterScriptCallback("on_option_change", on_option_change)
	on_option_change(ui_mcm)
end