name: Addon Package
on:
  release:
    types: published
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix of the addon package'
        required: true
        type: string

permissions: 
  contents: write

jobs:
  release-packaging:
    if: ${{ github.event_name == 'release' }}
    name: Release Package Addon
    runs-on: windows-latest
    env:
      package_name: InspectWeapons_Expanded_${{ github.event.release.tag_name }}.zip
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6.0.2
      with:
        ref: ${{ github.event.repository.default_branch }}
    - name: Packaging
      shell: powershell
      run: Compress-Archive -Path src/* -Destination ${{ env.package_name }}
    - name: Release Addon
      uses: AButler/upload-release-assets@v3.0.1
      with:
        files: ${{ env.package_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.event.release.tag_name }}

  manual-packaging:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Manual Package Addon
    runs-on: windows-latest
    env:
      package_name: InspectWeapons_Expanded_${{ inputs.suffix }}.zip
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6.0.2
      with:
        ref: ${{ github.event.ref }}
    - name: Packaging
      shell: powershell
      run: Compress-Archive -Path src/* -Destination ${{ env.package_name }}
    - name: Upload Artefact
      uses: actions/upload-artifact@v7.0.0
      with:
        path: ${{ env.package_name }}
        archive: false
